# Generated by Django 2.2.4 on 2019-08-06 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='select_quantity',
        ),
    ]
