# Generated by Django 2.2.3 on 2019-08-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0002_remove_product_select_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password1', models.CharField(max_length=20)),
                ('password2', models.CharField(max_length=20)),
                ('mobile_no', models.CharField(max_length=11)),
                ('account_type', models.CharField(choices=[('BUYER', 'BUYER'), ('SELLER', 'SELLER')], max_length=8)),
            ],
            options={
                'unique_together': {('email',)},
            },
        ),
    ]
