# Generated by Django 2.2.3 on 2019-08-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0006_producthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='name',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='total_price',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
