# Generated by Django 2.2.3 on 2019-08-07 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0007_auto_20190807_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producthistory',
            old_name='name',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='producthistory',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
