# Generated by Django 2.2.3 on 2019-08-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0009_auto_20190807_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='producthistory',
            name='select_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
