# Generated by Django 2.2.3 on 2019-08-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0010_producthistory_select_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthistory',
            name='email',
            field=models.EmailField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='product_name',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='select_quantity',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='total_price',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='producthistory',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
