# Generated by Django 2.2.3 on 2019-08-08 19:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0012_auto_20190808_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherform',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
