# Generated by Django 2.2.3 on 2019-08-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0013_otherform_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='update_on',
        ),
    ]
